name: test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
         python-version: '3.10'
         
      - name: Install requirements
        run: |
          pip3 install pyinstaller
          pip3 install requests
          
      - name: Build
        run: pyinstaller -F qbittorrent_autoupdatetracker.py
        

      
    Upload:
      runs-on: ubuntu-20.04
      steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist

